const fs = require('fs');

const exercisesStr = `  {
    id: "chest_pushup",
    name: "Push-ups",
    muscle: "Chest",
    image: "/new/chest_pushup.png",
    tips: "Keep core tight. Lower until chest nearly touches the floor.",
    video: "https://www.youtube.com/results?search_query=proper+pushup+form",
    default_sets: 3,
    default_reps: 15,
  },
  {
    id: "chest_machine_press",
    name: "Machine Chest Press",
    muscle: "Chest",
    image: "/new/chest_machine_press.png",
    tips: "Keep back flat against the pad. Press until arms are fully extended.",
    video: "https://www.youtube.com/results?search_query=machine+chest+press+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "chest_decline_bench",
    name: "Decline Barbell Bench",
    muscle: "Chest",
    image: "/new/chest_decline_bench.png",
    tips: "Secure legs tightly. Targets the lower chest fibers.",
    video: "https://www.youtube.com/results?search_query=decline+bench+press+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "chest_svend_press",
    name: "Svend Press",
    muscle: "Chest",
    image: "/new/chest_svend_press.png",
    tips: "Squeeze plates together hard. Excellent for inner chest activation.",
    video: "https://www.youtube.com/results?search_query=svend+press+form",
    default_sets: 3,
    default_reps: 15,
  },
  {
    id: "back_t_bar_row",
    name: "T-Bar Row",
    muscle: "Back",
    image: "/new/back_t_bar_row.png",
    tips: "Use a V-grip handle. Keep lower back straight and pull towards your stomach.",
    video: "https://www.youtube.com/results?search_query=t-bar+row+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "back_straight_arm_pulldown",
    name: "Straight Arm Pulldown",
    muscle: "Back",
    image: "/new/back_straight_arm_pulldown.png",
    tips: "Keep arms straight with a slight bend. Push down using your lats.",
    video: "https://www.youtube.com/results?search_query=straight+arm+pulldown+form",
    default_sets: 3,
    default_reps: 15,
  },
  {
    id: "legs_hack_squat",
    name: "Hack Squat",
    muscle: "Legs",
    image: "/new/legs_hack_squat.png",
    tips: "Place feet shoulder-width. Keep back tight against the pad and go deep.",
    video: "https://www.youtube.com/results?search_query=machine+hack+squat",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "legs_bulgarian",
    name: "Bulgarian Split Squat",
    muscle: "Legs",
    image: "/new/legs_bulgarian_split_squat.png",
    tips: "Keep chest up and drop the back knee straight down.",
    video: "https://www.youtube.com/results?search_query=bulgarian+split+squat+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "legs_standing_calf",
    name: "Standing Calf Raises",
    muscle: "Legs",
    image: "/new/legs_standing_calf_raises.png",
    tips: "Explode up, hold for a second, then lower slowly.",
    video: "https://www.youtube.com/results?search_query=standing+calf+raises+form",
    default_sets: 4,
    default_reps: 15,
  },
  {
    id: "legs_glute_bridge",
    name: "Barbell Glute Bridge",
    muscle: "Legs",
    image: "/new/legs_glute_bridge.png",
    tips: "Drive through your heels and squeeze your glutes at the top.",
    video: "https://www.youtube.com/results?search_query=barbell+glute+bridge+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "shoulders_upright_row",
    name: "Upright Row",
    muscle: "Shoulders",
    image: "/new/shoulders_upright_row.png",
    tips: "Pull the weight up leading with your elbows.",
    video: "https://www.youtube.com/results?search_query=upright+row+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "shoulders_arnold_press",
    name: "Arnold Press",
    muscle: "Shoulders",
    image: "/new/shoulders_arnold_press.png",
    tips: "Start with palms facing you and rotate out as you press up.",
    video: "https://www.youtube.com/results?search_query=arnold+press+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "shoulders_face_pulls",
    name: "Cable Face Pulls",
    muscle: "Shoulders",
    image: "/new/shoulders_face_pulls.png",
    tips: "Pull the rope towards your eyes, flaring elbows out.",
    video: "https://www.youtube.com/results?search_query=cable+face+pulls+form",
    default_sets: 3,
    default_reps: 15,
  },
  {
    id: "shoulders_front_raise",
    name: "Dumbbell Front Raise",
    muscle: "Shoulders",
    image: "/new/shoulders_front_raise.png",
    tips: "Raise the dumbbells in front of you until parallel to the floor.",
    video: "https://www.youtube.com/results?search_query=dumbbell+front+raise+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "shoulders_shrugs",
    name: "Dumbbell Shrugs",
    muscle: "Shoulders",
    image: "/new/shoulders_shrugs.png",
    tips: "Shrug your shoulders straight up towards your ears and hold.",
    video: "https://www.youtube.com/results?search_query=dumbbell+shrugs+form",
    default_sets: 3,
    default_reps: 15,
  },
  {
    id: "arms_preacher_curl",
    name: "Preacher Curl",
    muscle: "Arms",
    image: "/new/arms_preacher_curl.png",
    tips: "Keep armpits flushed against the pad. Squeeze hard at the top.",
    video: "https://www.youtube.com/results?search_query=ez+bar+preacher+curl",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "arms_tricep_kickback",
    name: "Dumbbell Tricep Kickback",
    muscle: "Arms",
    image: "/arm/arm2.png",
    tips: "Keep elbows glued to your sides and extend the arm fully backwards.",
    video: "https://www.youtube.com/results?search_query=tricep+kickback+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "arms_concentration_curl",
    name: "Concentration Curl",
    muscle: "Arms",
    image: "/arm/arm3.png",
    tips: "Rest your elbow on your inner thigh for stability.",
    video: "https://www.youtube.com/results?search_query=concentration+curl+form",
    default_sets: 3,
    default_reps: 12,
  },
  {
    id: "arms_skull_crushers",
    name: "EZ Bar Skullcrushers",
    muscle: "Arms",
    image: "/arm/arm4.png",
    tips: "Lower the bar towards your forehead, keep elbows pointing up.",
    video: "https://www.youtube.com/results?search_query=ez+bar+skullcrushers",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "core_russian_twist",
    name: "Russian Twists",
    muscle: "Core",
    image: "/core/core1.png",
    tips: "Rotate your torso, not just your arms. Use a weight if easy.",
    default_sets: 3,
    default_reps: 20,
  },
  {
    id: "core_hanging_leg_raise",
    name: "Hanging Leg Raise",
    muscle: "Core",
    image: "/core/core2.png",
    tips: "Hang from a bar and raise straight legs up towards your chest.",
    video: "https://www.youtube.com/results?search_query=hanging+leg+raise+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "core_ab_wheel",
    name: "Ab Wheel Rollout",
    muscle: "Core",
    image: "/core/core3.png",
    tips: "Keep your lower back slightly rounded to protect the spine.",
    video: "https://www.youtube.com/results?search_query=ab+wheel+rollout+form",
    default_sets: 3,
    default_reps: 10,
  },
  {
    id: "core_bicycle_crunches",
    name: "Bicycle Crunches",
    muscle: "Core",
    image: "/core/core4.png",
    tips: "Opposite elbow to opposite knee. Twist the torso completely.",
    video: "https://www.youtube.com/results?search_query=bicycle+crunches+form",
    default_sets: 3,
    default_reps: 20,
  },
  {
    id: "core_declined_situp",
    name: "Decline Sit-Ups",
    muscle: "Core",
    image: "/core/core5.png",
    tips: "Perform regular sit-ups backwards on a decline bench for max tension.",
    video: "https://www.youtube.com/results?search_query=decline+sit-ups",
    default_sets: 3,
    default_reps: 15,
  }`;

let c = fs.readFileSync('./src/data/exercises.js', 'utf8');

// Find the precise split point which works across all OS
const programIdx = c.indexOf('export const workoutPrograms = {');
if (programIdx > -1) {
  const bracketIdx = c.lastIndexOf('];', programIdx);
  if (bracketIdx > -1) {
    c = c.substring(0, bracketIdx) + ',\n' + exercisesStr + '\n' + c.substring(bracketIdx);
  }
}

c = c.replace('"chest_flat_db_fly",', '"chest_pushup",').replace('"chest_dips",', '"chest_machine_press",');
c = c.replace('"back_reverse_bb_row",', '"back_t_bar_row",').replace('"back_extensions",', '"back_straight_arm_pulldown",');
c = c.replace('"sh_shrugs",', '"shoulders_arnold_press",').replace('"sh_face_pulls_sh",', '"shoulders_upright_row",');
c = c.replace('"arm_wrist_curl",', '"arms_skull_crushers",').replace('"arm_reverse_curl",', '"arms_preacher_curl",');
c = c.replace('"leg_adductor",', '"legs_hack_squat",').replace('"leg_calf_raise",', '"legs_bulgarian",');

fs.writeFileSync('./src/data/exercises.js', c);
console.log('Injection successful:', c.includes('chest_pushup'));
